export const ChartErrorCode = {
  // Data validation errors
  INVALID_DATA_SERIES: 'INVALID_DATA_SERIES',
  MISSING_DATA_POINTS: 'MISSING_DATA_POINTS',
  INVALID_SERIES_INDEX: 'INVALID_SERIES_INDEX',
  
  // Chart type errors
  UNSUPPORTED_CHART_TYPE: 'UNSUPPORTED_CHART_TYPE',
  INVALID_CHART_CONFIG: 'INVALID_CHART_CONFIG',
  
  // Animation errors
  INVALID_ANIMATION_STYLE: 'INVALID_ANIMATION_STYLE',
  ANIMATION_INIT_FAILED: 'ANIMATION_INIT_FAILED',
  
  // Rendering errors
  CHART_RENDER_FAILED: 'CHART_RENDER_FAILED',
  OPTION_GENERATION_FAILED: 'OPTION_GENERATION_FAILED',
  
  // State errors
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  STATE_UPDATE_FAILED: 'STATE_UPDATE_FAILED'
} as const;

export type ChartErrorCode = typeof ChartErrorCode[keyof typeof ChartErrorCode];